name: Setup Java 7 via SDKMAN
description: Installs SDKMAN and Zulu JDK 7.0.352, and outputs JAVA 7 home path for Maven toolchains.xml
runs:
  using: composite
  steps:
    - name: Install SDKMAN
      shell: bash
      run: |
        curl -s "https://get.sdkman.io?ci=true" | bash

    - id: install
      name: Install Zulu JDK 7.0.352 via SDKMAN
      shell: bash
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install java 7.0.352-zulu < /dev/null
        JAVA7_HOME="$(sdk home java 7.0.352-zulu)"
        echo "java7_home=$JAVA7_HOME" >> "$GITHUB_OUTPUT"

outputs:
  java7_home:
    description: Path to installed Java 7 (Zulu 7.0.352)
    value: ${{ steps.install.outputs.java7_home }}
