name: Setup Java 7 (Zulu) and write toolchains
description: Installs Zulu JDK 7 via actions/setup-java and writes ~/.m2/toolchains.xml for Maven toolchain version 7
runs:
  using: composite
  steps:
    - name: Install Zulu JDK 7
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '7'
        cache: maven
